# Project Information
site_name: Automated Stata summary tables
site_description: 'Stata code to make and export summary tables in an automated fashion'
site_author: 'Kyle Barron'

docs_dir: 'docs'
site_dir: 'site'

# Repository
repo_name: 'stata-notes-table'
repo_url: 'https://github.com/kylebarron/stata-notes-table'

# Layout
pages:
    - Home: 'index.md'

# Copyright
copyright: 'Copyright &copy; 2018 Mauricio Cáceres Bravo and Kyle Barron'

# Theme
theme:
    logo:
        icon: 'local_library'
    name: 'material'
    language: 'en'
    palette:
        primary: 'orange'
        accent:  'light blue'
    font:
        text: 'Nunito Sans'
        code: 'Fira Code'

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - meta
    - pymdownx.arithmatex
    - pymdownx.smartsymbols:
        fractions: false
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - toc:
        permalink: true
